name: Build macos

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'gobgoblin-macos'
          #options: --onefile, --name "My App", --windowed
