name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.13

    - name: Activate virtual environment
      run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      
    - name: pip intaller 
      run: pip install
      
    - name: PyInstaller Windows
      run: pyinstaller app.py

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-build
        path: ./dist
   
 
          
          
